# Reflections {#reflections}


Shattered mirror reflections 

seeded down the street along the night.

Tall trees branches bare

beneath my feet run clouds.

And like a flower that opens the night

a swatch of sky in a ray of sunshine:

a sketch of light melts down the street

turns into a shadow, a Flash

of elsewhere. And I, who are just a reflection

in this nothing copyright, another

myself. An image skewed.

A pebble thrown among puddles scattered

my circulars horizons.


## Riflessioni (the Italian original version) {-}

Frantumi di specchio seminati

per strada lungo la notte.

Alberi altissimi dai rami scarni

sotto i miei piedi corrono nuvole.

E come un fiore che si apre la notte

un ritaglio di cielo in un raggio di sole:

uno schizzo di luce si scioglie per strada

si trasforma in un’ombra, uno sprazzo

d’altrove. E io, che sono solo un riflesso

in questo nulla d’autore, un altro

me stesso. Un’immagine obliqua.

Un sassolino gettato tra pozzanghere sparse

i miei circolari orizzonti.

